%define with_java 0
%define with_check 0

Summary: A GNU general-purpose parser generator
Summary(zh_CN.UTF-8): GNU通用目的解析生成器
Name: bison
Version: 2.5
Release: 1%{?dist}
License: GPLv3+
Group: Development/Tools
Group(zh_CN.UTF-8): 开发/工具
Source: ftp://ftp.gnu.org/pub/gnu/bison/bison-%{version}.tar.bz2

# testsuite patch and a dependency
Patch0: bison-2.4.2-drop-test-67.patch
BuildRequires: autoconf

URL: http://www.gnu.org/software/bison/
BuildRoot: %{_tmppath}/%{name}-root
BuildRequires: m4 >= 1.4 
%if %{with_java}
BuildRequires: java-1.6.0-openjdk-devel
%endif
Requires: m4 >= 1.4
Requires(post): /sbin/install-info
Requires(preun): /sbin/install-info

%description
Bison is a general purpose parser generator that converts a grammar
description for an LALR(1) context-free grammar into a C program to
parse that grammar. Bison can be used to develop a wide range of
language parsers, from ones used in simple desk calculators to complex
programming languages. Bison is upwardly compatible with Yacc, so any
correctly written Yacc grammar should work with Bison without any
changes. If you know Yacc, you shouldn't have any trouble using
Bison. You do need to be very proficient in C programming to be able
to use Bison. Bison is only needed on systems that are used for
development.

If your system will be used for C development, you should install
Bison.

%description -l zh_CN.UTF-8
Bison是通用目的解析生成器. 它将LALR(1)上下文无关文法的描述转化成
分析该文法的C程序. 一旦你精通Bison, 你可以用它生成从简单的桌面计
算器到复杂的程序设计语言等等许多语言的分析器.

Bison向上兼容Yacc:所有书写正确的Yacc语法都应该可以不加更改地与
Bison一起工作. 熟悉Yacc的人能毫不费力地使用Bison. 你应该熟练地
掌握C程序设计语言,这样你才能使用Bison。

%package devel
Summary: -ly library for development using Bison-generated parsers
Summary(zh_CN.UTF-8): %{name} 的开发包
Group: Development/Libraries
Group(zh_CN.UTF-8): 开发/库
Provides: bison-static = %{version}-%{release}

%description devel
The bison-devel package contains the -ly library sometimes used by
programs using Bison-generated parsers.  If you are developing programs
using Bison, you might want to link with this library.  This library
is not required by all Bison-generated parsers, but may be employed by
simple programs to supply minimal support for the generated parsers.

# -ly is kept static.  It only contains two symbols: main and yyerror,
# and both of these are extremely simple (couple lines of C total).
# It doesn't really pay off to introduce a shared library for that.
#
# Therefore -devel subpackage could have been created as -static, but
# the split was done in Jan 2005, which predates current guidelines.
# Besides there is logic to that: the library is devel in the sense
# that the generated parser could be distributed together with other
# sources, and only bison-devel would be necessary to wrap the build.

%description devel -l zh_CN.UTF-8
bison-devel 包包含了使用 bison 生成解析器的 -ly 库，如果你要开发使用Bison
的程序，你可能需要链接这个库。

%package runtime
Summary: Runtime support files used by Bison-generated parsers
Summary(zh_CN.UTF-8): Bison 通用解析程序的运行环境支持文件
Group: Development/Libraries
Group(zh_CN.UTF-8): 开发/库

%description runtime
The bison-runtime package contains files used at runtime by parsers
that Bison generates.  Packages whose binaries contain parsers
generated by Bison should depend on bison-runtime to ensure that
these files are available.  See the Internationalization in the
Bison manual section for more information.

%description runtime -l zh_CN.UTF-8
Bison 通用解析程序的运行环境支持文件。

%prep
%setup -q
%patch0 -p1

%build
%configure
make

%if %{with_check}
%check
make check
#make maintainer-check
%endif

%install
rm -rf $RPM_BUILD_ROOT
%makeinstall

# Remove unpackaged files.
rm -f $RPM_BUILD_ROOT/%{_bindir}/yacc
rm -f $RPM_BUILD_ROOT/%{_infodir}/dir
rm -f $RPM_BUILD_ROOT/%{_mandir}/man1/yacc*

%find_lang %{name}
%find_lang %{name}-runtime

gzip -9nf ${RPM_BUILD_ROOT}%{_infodir}/bison.info*

%post
if [ -f %{_infodir}/bison.info.gz ]; then # for --excludedocs
   /sbin/install-info %{_infodir}/bison.info.gz %{_infodir}/dir --entry="* bison: (bison).                        The GNU parser generator." || :
fi

%preun
if [ $1 = 0 ]; then
    if [ -f %{_infodir}/bison.info.gz ]; then # for --excludedocs
      /sbin/install-info --delete %{_infodir}/bison.info.gz %{_infodir}/dir --entry="* bison: (bison).                        The GNU parser generator." || :
    fi
fi

# The distribution contains also source files.  These are used by m4
# when the target parser file is generated.
%files -f %{name}.lang
%defattr(-,root,root)
%doc AUTHORS ChangeLog NEWS OChangeLog README THANKS TODO COPYING
%{_mandir}/*/bison*
%{_datadir}/bison
%{_infodir}/bison.info*
%{_bindir}/bison
%{_datadir}/aclocal/bison*.m4

%files -f %{name}-runtime.lang runtime
%doc COPYING

%files devel
%doc COPYING
%defattr(-,root,root)
%{_libdir}/liby.a

%clean
rm -rf $RPM_BUILD_ROOT

%changelog
* Wed Nov 02 2011 Liu Di <liudidi@gmail.com> - 2.5-1
- 更新到 2.5
